server:
 port: 8081
 servlet:
  context-path: /auth

spring:
    ldap:
     embedded:
      base-dn: dc=springframework,dc=org
      ldif: classpath:test-server.ldif
      port: 8389
      url: ldap://localhost:8389/

client:
  id: henry
  secret: secret
  redirect: http://localhost:8082/ui/index
        