server:
  port: 8082
  servlet:
    context-path: /ui

spring:
  security:
    basic:
      enabled: false
    oauth2:
      client:
        registration:
          auth:
            client-id: henry
            client-secret: secret
            client-authentication-method: basic
            scope: user_info
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/ui/index
        provider:
          auth:
            authorization-uri: http://localhost:8081/auth/oauth/authorize
            token-uri: http://localhost:8081/auth/oauth/token
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
